# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ta-watanabe-terraform-state"
    dynamodb_table = "watanabe-terraform-lock-table"
    encrypt        = true
    key            = "aws_waf_regex_pattern_set/terraform.tfstate"
    region         = "ap-northeast-1"
  }
}
