services:
  terragrunt:
    build:
      context: .
      dockerfile: ./containers/Dockerfile
    volumes:
      - ./:/terraform
      - ~/.aws:/root/.aws
    working_dir: /terraform/environments
    entrypoint: sh
    environment:
      - AWS_CONFIG_FILE=/root/.aws/config
      - AWS_SSO_SESSION=pm_local_session
      - AWS_PROFILE=${AWS_PROFILE}