# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ta-watanabe-terraform-state"
    dynamodb_table = "watanabe-terraform-lock-table"
    encrypt        = true
    key            = "CloudWatch-Logs-to-Slack/lb_5XX_alarm_and_topic/terraform.tfstate"
    region         = "ap-northeast-1"
  }
}
